# Generated by Django 6.0.7 on 2026-08-02 10:06
#
# Initial migration for the `core` app: creates the schema for a train/station
# management system (trains, stations, platforms, passengers, bookings,
# arrivals) plus a log table written by the background agents.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # First migration for this app — no prior migration state exists.
    initial = True

    # No other app/migration must run before this one.
    dependencies = [
    ]

    # Ordering matters: models referenced by ForeignKeys (Station, Train,
    # Passenger) are created before the models that point at them
    # (Platform, Booking, Arrival).
    operations = [
        # Audit/telemetry trail of what each agent did and when.
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                # Django's implicit auto-incrementing primary key.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Name/identifier of the agent that emitted this entry.
                ('agent', models.CharField(max_length=40)),
                # Log level: 'info', 'warn', 'error', etc. Plain text, not a choices field.
                ('severity', models.CharField(default='info', max_length=10)),
                # Free-form log body; TextField so length is unbounded.
                ('message', models.TextField()),
                # Simulation clock time as "HH:MM" (max_length=5), not a real time column.
                ('logged_at', models.CharField(max_length=5)),
                # Real wall-clock insert timestamp, set automatically on create.
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # A person who can hold bookings.
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                # Stored as text so leading zeros / '+' country codes survive.
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        # A physical station; owns one or more platforms.
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                # Short station code (e.g. "DHK") — unique, so it can act as a natural key.
                ('code', models.CharField(max_length=10, unique=True)),
                # Live headcount inside the station, updated as passengers arrive/leave.
                ('passengers_on_site', models.IntegerField(default=0)),
                # Maximum safe headcount; compared against passengers_on_site for crowding alerts.
                ('capacity', models.IntegerField()),
            ],
        ),
        # A train service and its static route/schedule facts.
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                # Service number (e.g. "705") — unique identifier for the train.
                ('number', models.CharField(max_length=10, unique=True)),
                # Route endpoints stored as plain text rather than FKs to Station.
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                # Route length; used for delay-recovery / running-time estimates.
                ('distance_km', models.IntegerField(default=200)),
                # Planned intermediate stops; more halts means less room to make up time.
                ('scheduled_halts', models.IntegerField(default=8)),
            ],
        ),
        # A platform belonging to a station. Created after Station because of the FK.
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Platform label ("1", "2A") — text, since it isn't always numeric.
                ('number', models.CharField(max_length=4)),
                # Current number of people waiting on this platform.
                ('occupancy', models.IntegerField(default=0)),
                # Safe standing capacity for this platform.
                ('capacity', models.IntegerField()),
                # Train currently expected here; nullable when the platform is idle.
                ('waiting_for', models.CharField(blank=True, max_length=80, null=True)),
                # Last crowding alert emitted, kept so the same alert isn't sent twice.
                ('last_alert_level', models.CharField(blank=True, max_length=10, null=True)),
                # Deleting a station removes its platforms; access via station.platforms.all().
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.station')),
            ],
        ),
        # One passenger's seat on one train for a given date, plus live status.
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Date of travel as free text (e.g. "2026-08-02") rather than a DateField.
                ('travel_date', models.CharField(max_length=20)),
                # Timetabled departure, "HH:MM".
                ('scheduled_departure', models.CharField(max_length=5)),
                # Current best estimate of departure, "HH:MM"; updated as delays change.
                ('expected_departure', models.CharField(max_length=5)),
                # Assigned platform; null until it is announced.
                ('platform', models.CharField(blank=True, max_length=4, null=True)),
                # Coach/car assignment; null until allocated.
                ('coach', models.CharField(blank=True, max_length=30, null=True)),
                # 'on-time', 'delayed', 'cancelled', etc.
                ('status', models.CharField(default='on-time', max_length=10)),
                # Minutes currently late.
                ('delay_minutes', models.IntegerField(default=0)),
                # Minutes clawed back en route (e.g. by skipping slack time).
                ('recovered_minutes', models.IntegerField(default=0)),
                # Human-readable explanation written by the agent for this booking.
                ('agent_note', models.TextField(blank=True, null=True)),
                # Departure time last pushed to the passenger; compare with
                # expected_departure to decide whether a new notification is needed.
                ('notified_departure', models.CharField(blank=True, max_length=5, null=True)),
                # Deleting a passenger or train deletes their bookings.
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.passenger')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.train')),
            ],
        ),
        # An inbound service at a station — the arrivals board.
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Timetabled arrival, "HH:MM".
                ('scheduled', models.CharField(max_length=5)),
                # Live estimated arrival, "HH:MM".
                ('expected', models.CharField(max_length=5)),
                # Arrival platform; null until assigned.
                ('platform', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(default='on-time', max_length=10)),
                # Station this arrival belongs to; reachable via station.arrivals.all().
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.station')),
                # No related_name, so reverse lookups use train.arrival_set.
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
    ]