# Generated by Django 6.0.7 on 2026-08-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=40)),
                ('severity', models.CharField(default='info', max_length=10)),
                ('message', models.TextField()),
                ('logged_at', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('passengers_on_site', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('distance_km', models.IntegerField(default=200)),
                ('scheduled_halts', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('occupancy', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
                ('waiting_for', models.CharField(blank=True, max_length=80, null=True)),
                ('last_alert_level', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.CharField(max_length=20)),
                ('scheduled_departure', models.CharField(max_length=5)),
                ('expected_departure', models.CharField(max_length=5)),
                ('platform', models.CharField(blank=True, max_length=4, null=True)),
                ('coach', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='on-time', max_length=10)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('recovered_minutes', models.IntegerField(default=0)),
                ('agent_note', models.TextField(blank=True, null=True)),
                ('notified_departure', models.CharField(blank=True, max_length=5, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.passenger')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.train')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.CharField(max_length=5)),
                ('expected', models.CharField(max_length=5)),
                ('platform', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(default='on-time', max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
    ]
