# Generated by Django 6.0.7 on 2026-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='route',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
