# Generated by Django 6.0.7 on 2026-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_train_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seat_classes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
