# Generated by Django 6.0.7 on 2026-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_train_seat_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('auth_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nid_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nid_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
