# Generated by Django 6.0.7 on 2026-08-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stationmanager_passenger_auth_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('passenger', 'Passenger'), ('authority', 'Authority')], max_length=10)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('nid_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('authority_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_by', to='core.authorityid')),
            ],
        ),
        migrations.DeleteModel(
            name='StationManager',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='nid_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='nid_verified',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='passenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='core.passenger'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
