# Generated by Django 6.0.7 on 2026-08-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='confirmed', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fare_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='station',
            name='division',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='seat_capacity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers_detail', to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('arrival', models.CharField(blank=True, max_length=5, null=True)),
                ('departure', models.CharField(blank=True, max_length=5, null=True)),
                ('distance_km', models.FloatField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_stops', to='core.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.train')),
            ],
            options={
                'ordering': ['train', 'sequence'],
            },
        ),
    ]
