# Generated by Django 6.0.7 on 2026-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """Index the filter behind live seat availability.

    Every route search, seat map and booking counts free seats by scanning
    Booking for one train/date/class that is still confirmed. Adding rows
    only - no column is added, changed or dropped, so existing bookings are
    untouched.
    """


    dependencies = [
        ('core', '0007_booking_booking_status_booking_destination_station_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['train', 'travel_date', 'seat_class', 'booking_status'], name='booking_availability_idx'),
        ),
    ]
